[package]
name = "toydb"
description = "A distributed SQL database"
version = "0.1.0"
authors = ["Erik Grinaker <erik@grinaker.org>"]
edition = "2018"
default-run = "toydb"

[dependencies]
clap = "~2.33.0"
config = "~0.9.3"
crossbeam-channel = "~0.4.0"
grpc = "~0.6.1"
lazy_static = "~1.4.0"
log = "~0.4.6"
protobuf = "~2.8.1"
rand = "~0.7.2"
regex = "~1.3.1"
rmp-serde = "~0.14.0"
rustyline = "~5.0.0"
serde = "~1.0.91"
serde_derive = "~1.0.91"
simplelog = "~0.7.4"
uuid = { version = "~0.8.1", features = ["v4"] }

# The following are sub-dependencies that we need for error handling
httpbis = "~0.7.0"

[build-dependencies]
protoc-rust-grpc = "~0.6.1"

[dev-dependencies]
assert_matches = "~1.3.0"
goldenfile = "~1.1.0"
tempfile = "~3.1.0"