[package]
name = "toydb"
description = "A distributed SQL database"
version = "0.1.0"
authors = ["Erik Grinaker <erik@grinaker.org>"]
edition = "2018"

[dependencies]
clap = "~2.33.0"
config = "~0.9.3"
grpc = "~0.6.1"
log = "~0.4.6"
protobuf = "~2.5.0"
rand = "~0.6.5"
serde = "~1.0.91"
serde_derive = "~1.0.91"
simplelog = "~0.5.3"

# The following are sub-dependencies that we need for error handling
httpbis = "~0.7.0"

[build-dependencies]
protoc-rust-grpc = "~0.6.1"