# The cluster node ID and peer ID/address map (empty for single node)
id: toydb
peers: {}

# Network addresses to bind the SQL and Raft servers to
listen_sql: 0.0.0.0:9605
listen_raft: 0.0.0.0:9705

# The node log level, data directory, and whether to fsync writes
log_level: INFO
data_dir: /var/lib/toydb
sync: true
