# The cluster node ID (must be unique), data directory, and log level
id: toydb
data_dir: /var/lib/toydb
log_level: INFO

# Network addresses to bind the SQL and Raft servers to
listen_sql: 0.0.0.0:9605
listen_raft: 0.0.0.0:9705

# ID/address map of other cluster peers (empty for single node)
peers: {}
